// @formatter:off
// SPDX-FileCopyrightText: 2017-2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
// @formatter:on
package net.ladenthin.bitcoinaddressfinder.statistics;

import java.util.Map;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.LongSupplier;
import lombok.ToString;

/**
 * Shared, thread-safe runtime metrics written by the producers and read by the consumer's
 * periodic statistics line. A single instance is created by the orchestrator
 * ({@code Finder}) and injected into every producer (which increment their batch counters)
 * and into the consumer (which renders them).
 *
 * <p>Batch counts and generated-candidate counts are keyed by a per-producer label
 * ({@code "<keyProducerId> (<Strategy>, <CPU|GPU>)"}) so that multiple producers running
 * concurrently can be told apart in the log.
 *
 * <p>{@code toString()} is generated by Lombok from the resolved accessors (the sorted snapshots
 * and the running-producer gauge value) rather than the raw fields, so the live
 * {@link LongSupplier} gauge is not dumped as a lambda identity.
 */
@ToString(onlyExplicitlyIncluded = true)
public class RuntimeStatistics {

    /** Creates a new, empty {@link RuntimeStatistics}. */
    public RuntimeStatistics() {}

    /** Dispatched-batch counts keyed by producer label. */
    private final ConcurrentMap<String, AtomicLong> batchesByProducer = new ConcurrentHashMap<>();

    /**
     * Generated candidate counts keyed by producer label.
     *
     * <p>The per-producer counterpart of {@link #generatedKeys}, and the only one of the two
     * per-producer maps that is comparable <em>between</em> producers: {@link #batchesByProducer}
     * counts dispatches, whose candidate yield is {@code 2^batchSizeInBits} and therefore differs
     * per producer. Two GPUs configured at {@code batchSizeInBits} 24 and 21 differ by 8× per batch,
     * so their batch counts read as a near-even split while the actual work split is 8× apart.
     */
    private final ConcurrentMap<String, AtomicLong> generatedKeysByProducer = new ConcurrentHashMap<>();

    /**
     * Total candidate keys generated across all producers (lifetime). This is what enters the
     * pipeline at the top — the producers' real output rate — as opposed to {@code checkedKeys} on
     * the consumer, which counts only the hash160 lookups that survive the GPU pre-filter and reach
     * LMDB. Kept here rather than derived from the batch count so it stays correct when producers
     * with different {@code batchSizeInBits} run concurrently.
     */
    private final AtomicLong generatedKeys = new AtomicLong();

    /**
     * Records {@code count} freshly generated candidate keys (one producer batch), both in the
     * lifetime total and in the per-producer breakdown.
     *
     * <p>The label is required rather than optional so the two totals cannot drift: a caller that
     * contributed to {@link #getGeneratedKeys()} without naming its producer would leave the
     * per-producer shares silently summing to less than the whole.
     *
     * @param producerLabel the producer label, e.g. {@code "exampleRandom (Random, GPU)"}
     * @param count         the number of candidates in the batch (its {@code getOverallWorkSize()})
     */
    public void addGeneratedKeys(String producerLabel, long count) {
        generatedKeys.addAndGet(count);
        generatedKeysByProducer
                .computeIfAbsent(producerLabel, key -> new AtomicLong())
                .addAndGet(count);
    }

    /**
     * Returns the lifetime total of generated candidate keys.
     *
     * @return candidates generated across all producers so far
     */
    public long getGeneratedKeys() {
        return generatedKeys.get();
    }

    /**
     * Late-bound gauge returning the number of producers currently in the {@code RUNNING}
     * state. Defaults to {@code 0} until the orchestrator wires the real supplier, because
     * the consumer's statistics timer starts before the producers are constructed.
     */
    private volatile LongSupplier runningProducersGauge = () -> 0L;

    /**
     * Records one dispatched batch for the given producer label.
     *
     * @param producerLabel the producer label, e.g. {@code "exampleRandom (Random, GPU)"}
     */
    public void incrementBatches(String producerLabel) {
        batchesByProducer
                .computeIfAbsent(producerLabel, key -> new AtomicLong())
                .incrementAndGet();
    }

    /**
     * Returns an ordered, immutable snapshot of the dispatched-batch counts per producer
     * label. Sorted by label so the rendered statistics line is stable across ticks.
     *
     * @return a sorted snapshot of batch counts keyed by producer label
     */
    @ToString.Include(name = "batchesByProducer")
    public Map<String, Long> batchesByProducerSnapshot() {
        return snapshotOf(batchesByProducer);
    }

    /**
     * Returns an ordered, immutable snapshot of the generated-candidate counts per producer label.
     * Sorted by label so the rendered statistics line is stable across ticks.
     *
     * @return a sorted snapshot of generated-candidate counts keyed by producer label
     */
    @ToString.Include(name = "generatedKeysByProducer")
    public Map<String, Long> generatedKeysByProducerSnapshot() {
        return snapshotOf(generatedKeysByProducer);
    }

    private static Map<String, Long> snapshotOf(ConcurrentMap<String, AtomicLong> counters) {
        Map<String, Long> snapshot = new TreeMap<>();
        counters.forEach((label, count) -> snapshot.put(label, count.get()));
        return snapshot;
    }

    /**
     * Wires the late-bound gauge used to report the number of currently-running producers.
     *
     * @param gauge supplier returning the count of producers in the {@code RUNNING} state
     */
    public void setRunningProducersGauge(LongSupplier gauge) {
        this.runningProducersGauge = gauge;
    }

    /**
     * Returns the current number of running producers.
     *
     * @return the running-producer count, or {@code 0} if the gauge has not been wired yet
     */
    @ToString.Include(name = "runningProducers")
    public long getRunningProducers() {
        return runningProducersGauge.getAsLong();
    }
}
