// SPDX-FileCopyrightText: 2017-2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.bitcoinaddressfinder.statistics;

import java.util.Map;
import java.util.stream.Collectors;

/**
 * Builds the human-readable statistics line printed by the consumer.
 */
public class Statistics {

    /** Creates a new {@link Statistics}. */
    public Statistics() {}

    /** Number of milliseconds per second. */
    @Deprecated
    public static final int ONE_SECOND_IN_MILLISECONDS = 1000;

    /**
     * Builds the periodic human-readable statistics line logged by the consumer.
     *
     * <p>The {@code Checked … keys} figure is the lifetime total; the keys/second and keys/minute
     * figures are the <em>current windowed</em> throughput (averaged over
     * {@code rateWindowSeconds}), not a lifetime average, so they track warm-up and thermal
     * throttling rather than settling to a long-run mean.
     *
     * @param uptime                       elapsed run time in milliseconds (lifetime)
     * @param keys                         total number of hash160 lookups against LMDB so far
     *                                     (lifetime) — i.e. candidates that survived any GPU
     *                                     pre-filter and reached the consumer
     * @param windowKeysPerSecond          current LMDB-lookup throughput in keys/second, averaged
     *                                     over the trailing {@code rateWindowSeconds} window
     * @param generatedKeys                total candidate keys generated by the producers so far
     *                                     (lifetime) — what enters the pipeline at the top, before
     *                                     any GPU pre-filter
     * @param windowGeneratedPerSecond     current candidate-generation throughput in keys/second,
     *                                     averaged over the same trailing window
     * @param rateWindowSeconds            the trailing window (seconds) the rate is averaged over
     * @param keysSumOfTimeToCheckContains cumulative time (ms) spent in presence lookups
     * @param batchesByProducer            dispatched-batch counts keyed by producer label
     *                                     ({@code "<keyProducerId> (<Strategy>, <CPU|GPU>)"}); lets
     *                                     concurrently running producers be told apart
     * @param producersRunning             number of producers currently in the RUNNING state
     * @param consumersRunning             number of consumer worker threads currently running
     * @param consumerReady               number of consume cycles the consumer was ready for work
     *                                     (empty queue, nothing to do); rising is normal/healthy — the
     *                                     CPU keeps up and an empty queue is the desired state
     * @param producerBlocked              number of times a producer hit a full queue on enqueue;
     *                                     rising is the warning sign — the consumer/CPU is too slow (CPU-bound)
     * @param keysQueueSize                current number of batches waiting in the queue
     * @param hits                         total number of address hits found so far
     * @return the formatted statistics message
     */
    public String createStatisticsMessage(
            long uptime,
            long keys,
            double windowKeysPerSecond,
            long generatedKeys,
            double windowGeneratedPerSecond,
            long rateWindowSeconds,
            long keysSumOfTimeToCheckContains,
            Map<String, Long> batchesByProducer,
            long producersRunning,
            long consumersRunning,
            long consumerReady,
            long producerBlocked,
            long keysQueueSize,
            long hits) {
        // calculate uptime (lifetime)
        long uptimeInSeconds = uptime / (long) ONE_SECOND_IN_MILLISECONDS;
        long uptimeInMinutes = uptimeInSeconds / 60;
        // calculate average contains time
        long averageContainsTime = keysSumOfTimeToCheckContains / Math.max(keys, 1);
        // per-producer batch breakdown, rendered as "label=count, label=count" (or "none")
        String batches = batchesByProducer.isEmpty()
                ? "none"
                : batchesByProducer.entrySet().stream()
                        .map(entry -> entry.getKey() + "=" + entry.getValue())
                        .collect(Collectors.joining(", "));

        // The two ends of the pipeline, side by side:
        //   Generated  = candidates the producers create (the GPU's real output rate).
        //   -> LMDB     = hash160 lookups that survive the GPU pre-filter and hit the consumer/LMDB.
        // The prominent rate used to be only the second one, which for a GPU-filtered run is a tiny
        // fraction of the actual work and made the tool look idle. Both are shown now, plus how much
        // the pre-filter removed before LMDB.
        String pruned = describeFilterEffect(windowGeneratedPerSecond, windowKeysPerSecond);

        return "Statistics: [uptime " + uptimeInMinutes + " min] [Generated "
                + formatRate(windowGeneratedPerSecond) + " (" + (generatedKeys / 1_000_000L) + " M total)] [-> LMDB "
                + formatRate(windowKeysPerSecond) + " (" + (keys / 1_000_000L) + " M lookups total)" + pruned
                + "] [rate window " + rateWindowSeconds + "s] [Batches per producer: " + batches
                + "] [Producers running: " + producersRunning + "] [Consumers running: " + consumersRunning
                + "] [Consumer ready for work (queue empty): " + consumerReady
                + "] [Producer blocked (queue full): " + producerBlocked + "] [Average contains time: "
                + averageContainsTime + " ms] [keys queue size: " + keysQueueSize + "] [Hits: " + hits + "]";
    }

    /**
     * Formats a per-second rate, auto-scaling to k/s, M/s or G/s so the number stays readable across
     * the whole range (a starved consumer at a few thousand/s up to a GPU at hundreds of millions/s).
     *
     * @param perSecond the rate in units per second
     * @return e.g. {@code "130 M/s"}, {@code "2013 k/s"} or {@code "412/s"}
     */
    static String formatRate(double perSecond) {
        if (perSecond >= 1_000_000_000.0) {
            return Math.round(perSecond / 1_000_000_000.0) + " G/s";
        }
        if (perSecond >= 1_000_000.0) {
            return Math.round(perSecond / 1_000_000.0) + " M/s";
        }
        if (perSecond >= 1_000.0) {
            return Math.round(perSecond / 1_000.0) + " k/s";
        }
        return Math.round(perSecond) + "/s";
    }

    /**
     * Describes how much the GPU pre-filter removed before LMDB, as the share of the potential
     * hash160 lookups (two per generated candidate) that never reached the consumer.
     *
     * @param generatedPerSecond candidate-generation rate
     * @param lookupsPerSecond    LMDB-lookup rate (post-filter)
     * @return {@code ", NN.N% pre-filtered"}, or an empty string when there is not yet enough data
     */
    private static String describeFilterEffect(double generatedPerSecond, double lookupsPerSecond) {
        double potentialLookups = generatedPerSecond * 2.0; // compressed + uncompressed per candidate
        // Report only once candidates are generated and some (but not all) survive to LMDB. The
        // second test also covers the no-generation case (potentialLookups == 0, so any lookup rate
        // is >= it) and the full-transfer case (lookups reach the full potential, nothing filtered),
        // and it keeps the division safe: it runs only when 0 < lookupsPerSecond < potentialLookups.
        if (lookupsPerSecond <= 0.0 || lookupsPerSecond >= potentialLookups) {
            return "";
        }
        double prunedPercent = (1.0 - lookupsPerSecond / potentialLookups) * 100.0;
        return String.format(java.util.Locale.ROOT, ", %.2f%% pre-filtered", prunedPercent);
    }
}
